<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LFNQ669" failures="1" tests="5" name="Retry clss" time="10.374" errors="0" timestamp="2022-05-22T06:58:56 EDT">
  <testcase classname="ui.ListenerDemoTestforRetry" name="launchApp" time="6.152">
    <skipped/>
  </testcase> <!-- launchApp -->
  <testcase classname="ui.ListenerDemoTestforRetry" name="launchApp" time="1.136">
    <skipped/>
  </testcase> <!-- launchApp -->
  <testcase classname="ui.ListenerDemoTestforRetry" name="launchApp" time="0.786">
    <skipped/>
  </testcase> <!-- launchApp -->
  <testcase classname="ui.ListenerDemoTestforRetry" name="launchApp" time="1.145">
    <skipped/>
  </testcase> <!-- launchApp -->
  <testcase classname="ui.ListenerDemoTestforRetry" name="launchApp" time="1.097">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ui.ListenerDemoTestforRetry.launchApp(ListenerDemoTestforRetry.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- launchApp -->
</testsuite> <!-- Retry clss -->
